### ISSUE TITLE
Wrong Title: on lists

### ISSUE THREAD

**Issue by RicoHeat** [cbuijs/hblock#1]
Hello my friend @cbuijs .. I've noticed that for the hBlock and 1hosts 'adblock' lists the title descriptions have HaGeZi on them. I'm not sure if some of the other lists also have the wrong name so maybe check just incase.

Thanks for your work.. Have a great day! 👍

**Comment by cbuijs** [comment]
Hi @RicoHeat , big OOPS!!! I copied the script I use for Hagezi and forgot to modify the descriptions... 

Thanks for the heads-up. Will fix it probably today and will be reflected within 24 hours or so.

Will check the other ones as well just to make sure.

Big thanks for notifying me!

**Comment by RicoHeat** [comment]
Closed

**Comment by cbuijs** [comment]
Fixed.
